DROP TABLE IF EXISTS Blogs CASCADE;
DROP TABLE IF EXISTS Blogtags CASCADE;
DROP TABLE IF EXISTS Comments CASCADE;
DROP TABLE IF EXISTS Posts CASCADE;
DROP TABLE IF EXISTS Posts_reaction CASCADE;
DROP TABLE IF EXISTS Tags CASCADE;
DROP TABLE IF EXISTS Users CASCADE;
